apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

configMapGenerator:
  - name: grafana-dashboard-node-exporter-full
    files:
      - node-exporter-full.json
    options:
      labels:
        grafana_dashboard: "1"
      disableNameSuffixHash: true
