# Handlers for common role

---
- name: Restart SSH
  service:
    name: ssh
    state: restarted

- name: Reboot required
  reboot:
    msg: "Rebooting for cgroups/kernel changes"
    reboot_timeout: 300
